### ISSUE TITLE
"Problem parsing package" error on android 

### ISSUE THREAD

**Issue by Codegobler** [Team-xManager/xManager#522]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung Galaxy A50
- Android Version: 11 
- ROM Version:  stock
- xManager Version: 5.6
```

### 📝 Description

1.Download latest Amoled patch
2."there was a problem while parsing the package" error
3.same thing for all patches
...

### 📸 Screenshots

![Screenshot_20240719-224236_Package installer](https://github.com/user-attachments/assets/cd6ecaef-747d-44ef-b7ba-b3d0972ef191)

**Comment by JakobHunterek** [comment]
Settings > Refetch and Reboot
Let me know if this resolves the issue

**Comment by Codegobler** [comment]
It worked
Thank you very much

**Comment by xC3FFF0E** [comment]
Resolved. Closing.

**Comment by wknjk** [comment]
Hi, this "Settings > Refetch and Reboot" doesn't work for me. I still have the same error
Phone: Samsung s20+
Android version: 13
XManager version: 5.6

**Comment by Flamee0409** [comment]
It doesn't work for me neither 
Phone: Samsung Galaxy S10+
Android version: 12
XManager version: 5.6

**Comment by Flamee0409** [comment]
It doesn't work for me neither 
Phone: Samsung Galaxy S10+
Android version: 12
XManager version: 5.6

**Comment by Alex25456** [comment]
You can download it by simply taping on the latest release once it shows there is an existent file press on delete so it will delete the file and press again on the latest 8.9.18.512 you should see mirror link, once you click it it will take you to website to download it and it will work from there.

**Comment by Flamee0409** [comment]
It worked. Thanks!
